name: build
on: [push, pull_request]
jobs:
  build_matrix:
    strategy:
      matrix:
        distro: [Alpine, Arch, FreeBSD]
        include:
          - distro: Alpine
            container: alpine:edge
          - distro: Arch
            container: archlinux:base-devel
          - distro: FreeBSD
            env:
              SHPIPE: 'ssh freebsd sh -xe'
    runs-on: ubuntu-latest
    container: ${{ matrix.container }}
    steps:
        - name: packages-alpine
          if: matrix.distro == 'Alpine'
          run: |
            apk add clang gcc cairo-dev librsvg-dev libxkbcommon-dev meson musl-dev scdoc wayland-dev wayland-protocols
        - name: packages-arch
          if: matrix.distro == 'Arch'
          run: |
            pacman-key --init
            pacman -Syu --noconfirm
            pacman -S --noconfirm clang gcc meson cairo wayland wayland-protocols scdoc libxkbcommon
        - name: packages-freebsd
          if: matrix.distro == 'FreeBSD'
          uses: vmactions/freebsd-vm@v1
          with:
            prepare: |
              sed -i '' 's/quarterly/latest/' /etc/pkg/FreeBSD.conf
              pkg install -y cairo evdev-proto libepoll-shim libinotify librsvg2-rust meson pkgconf scdoc wayland wayland-protocols libxkbcommon
            run: echo 'Packages installed'
        # actions/checkout@v4 clones the repository
        - uses: actions/checkout@v4
        - name: set-arch-cflags
          if: matrix.distro == 'Arch'
          run: |
            export CFLAGS='-O2 -g -pipe -Wall -Wextra -Wpedantic -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -Wno-unused-parameter -Wpointer-arith -Wformat-security -Wunreachable-code -Wformat'
        - name: build-cc
          # No need to build with GCC on FreeBSD
          run: |
            echo '
              cd "$GITHUB_WORKSPACE"
              CC=cc meson setup build-cc
              ninja -C build-cc
            ' | ${SHPIPE:-sh -xe}
        - name: build-clang
          # FreeBSD's cc is already clang
          if: matrix.distro != 'FreeBSD'
          run: |
            CC=clang meson setup build-clang
            ninja -C build-clang
